import { describe, it, expect, beforeEach, vi } from "vitest";
import { render, screen, fireEvent } from "@testing-library/react";

const listProjectKeysQuery = vi.fn();
const latestQuery = vi.fn();
const rangeQuery = vi.fn();

vi.mock("@/lib/trpc/client", () => ({
  trpc: {
    reports: {
      listProjectKeys: { useQuery: (...a: unknown[]) => listProjectKeysQuery(...a) },
      getOwnByKeyLatest: { useQuery: (...a: unknown[]) => latestQuery(...a) },
      getOwnByKeyRange: { useQuery: (...a: unknown[]) => rangeQuery(...a) },
    },
  },
}));

// Stub usePermissions — can() is controllable per-test.
const canFn = vi.fn();
vi.mock("@/lib/usePermissions", () => ({
  usePermissions: () => ({
    can: canFn,
    perm: { userId: "user-1" },
    session: { coveredOrgs: ["org-1"] },
    isLoading: false,
  }),
}));

// Stub RubricEditor so we don't pull in its trpc dependencies.
vi.mock("@/components/evaluator/RubricEditor", () => ({
  RubricEditor: () => null,
}));

import { ProjectScoreSection } from "@/components/evaluator/ProjectScoreSection";

const KEY = {
  id: "11111111-1111-1111-1111-111111111111",
  name: "billing-service",
  userId: "u1",
  teamId: null,
  latestPeriodStart: "2026-06-01T00:00:00Z",
  revokedAt: null,
};

const REVOKED_KEY = {
  id: "22222222-2222-2222-2222-222222222222",
  name: "old-key",
  userId: "u1",
  teamId: null,
  latestPeriodStart: "2026-05-01T00:00:00Z",
  revokedAt: new Date("2026-05-15T00:00:00Z"),
};

describe("ProjectScoreSection", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    // Default: can() returns false so the rubric button is hidden unless overridden.
    canFn.mockReturnValue(false);
    // Sensible defaults for the by-key queries (only used once a key is picked).
    latestQuery.mockReturnValue({ data: undefined, isLoading: false });
    rangeQuery.mockReturnValue({ data: [], isLoading: false });
  });

  it("shows the loading state while listProjectKeys is in flight", () => {
    listProjectKeysQuery.mockReturnValue({ data: undefined, isLoading: true, error: null });
    render(<ProjectScoreSection />);
    expect(screen.getByText("Loading…")).toBeInTheDocument();
  });

  it("shows the empty state when no keys are opted in", () => {
    listProjectKeysQuery.mockReturnValue({ data: [], isLoading: false, error: null });
    render(<ProjectScoreSection />);
    expect(
      screen.getByText("No keys opted in for project scoring."),
    ).toBeInTheDocument();
    expect(
      screen.getByText(
        'Toggle "Score as project" on an API key to start tracking per-project scores.',
      ),
    ).toBeInTheDocument();
  });

  it("renders nothing when the listProjectKeys query errors", () => {
    listProjectKeysQuery.mockReturnValue({
      data: undefined,
      isLoading: false,
      error: { message: "boom" },
    });
    const { container } = render(<ProjectScoreSection />);
    expect(container).toBeEmptyDOMElement();
  });

  it("renders the key selector when keys are opted in", () => {
    listProjectKeysQuery.mockReturnValue({ data: [KEY], isLoading: false, error: null });
    render(<ProjectScoreSection />);

    const select = screen.getByLabelText("Select a project key…");
    expect(select).toBeInTheDocument();
    // Key name appears as an <option>.
    expect(screen.getByRole("option", { name: "billing-service" })).toBeInTheDocument();
    // No report is shown until a key is selected.
    expect(latestQuery).not.toHaveBeenCalled();
  });

  it("shows the per-key report once a key is selected", () => {
    listProjectKeysQuery.mockReturnValue({ data: [KEY], isLoading: false, error: null });
    latestQuery.mockReturnValue({
      data: {
        totalScore: "92.5000",
        periodStart: "2026-06-01T00:00:00Z",
        periodEnd: "2026-06-30T00:00:00Z",
        sectionScores: [],
        llmNarrative: null,
        llmModel: null,
        llmCalledAt: null,
      },
      isLoading: false,
    });
    rangeQuery.mockReturnValue({ data: [], isLoading: false });

    render(<ProjectScoreSection />);
    fireEvent.change(screen.getByLabelText("Select a project key…"), {
      target: { value: KEY.id },
    });

    // The score badge renders the latest total score to one decimal.
    expect(screen.getByText("92.5")).toBeInTheDocument();
  });

  it("shows the no-report state when the selected key has no report yet", () => {
    listProjectKeysQuery.mockReturnValue({ data: [KEY], isLoading: false, error: null });
    latestQuery.mockReturnValue({ data: null, isLoading: false });
    rangeQuery.mockReturnValue({ data: [], isLoading: false });

    render(<ProjectScoreSection />);
    fireEvent.change(screen.getByLabelText("Select a project key…"), {
      target: { value: KEY.id },
    });

    expect(
      screen.getByText("No report yet. Scores are generated by the nightly cron."),
    ).toBeInTheDocument();
  });

  it("renders a revoked key option with the revokedBadge suffix in the selector", () => {
    listProjectKeysQuery.mockReturnValue({
      data: [KEY, REVOKED_KEY],
      isLoading: false,
      error: null,
    });

    render(<ProjectScoreSection />);

    // Active key shows its name only.
    expect(screen.getByRole("option", { name: "billing-service" })).toBeInTheDocument();
    // Revoked key shows its name with "(revoked)" appended.
    expect(screen.getByRole("option", { name: "old-key (revoked)" })).toBeInTheDocument();
  });

  it("does not show Edit project rubric button when can() returns false", () => {
    // canFn defaults to false (set in beforeEach)
    listProjectKeysQuery.mockReturnValue({ data: [KEY], isLoading: false, error: null });
    render(<ProjectScoreSection />);
    fireEvent.change(screen.getByLabelText("Select a project key…"), {
      target: { value: KEY.id },
    });
    expect(screen.queryByRole("button", { name: /edit project rubric/i })).toBeNull();
  });

  it("shows Edit project rubric button when can() returns true", () => {
    canFn.mockReturnValue(true);
    listProjectKeysQuery.mockReturnValue({ data: [KEY], isLoading: false, error: null });
    render(<ProjectScoreSection />);
    fireEvent.change(screen.getByLabelText("Select a project key…"), {
      target: { value: KEY.id },
    });
    expect(screen.getByRole("button", { name: /edit project rubric/i })).toBeInTheDocument();
  });

  it("shows the revoked notice and no rerun affordance when a revoked key is selected", () => {
    listProjectKeysQuery.mockReturnValue({
      data: [REVOKED_KEY],
      isLoading: false,
      error: null,
    });
    latestQuery.mockReturnValue({
      data: {
        totalScore: "78.0000",
        periodStart: "2026-05-01T00:00:00Z",
        periodEnd: "2026-05-31T00:00:00Z",
        sectionScores: [],
        llmNarrative: null,
        llmModel: null,
        llmCalledAt: null,
        keyNameSnapshot: "old-key",
      },
      isLoading: false,
    });
    rangeQuery.mockReturnValue({ data: [], isLoading: false });

    render(<ProjectScoreSection />);
    fireEvent.change(screen.getByLabelText("Select a project key…"), {
      target: { value: REVOKED_KEY.id },
    });

    // Score still renders so historical data is accessible.
    expect(screen.getByText("78.0")).toBeInTheDocument();
    // Revoked notice must be visible.
    expect(screen.getByTestId("revoked-notice")).toBeInTheDocument();
    // No rerun/refresh button is shown for revoked keys.
    expect(screen.queryByRole("button", { name: /re.?run|refresh/i })).toBeNull();
  });
});
